version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
    volumes:
      - ./init_scripts:/docker-entrypoint-initdb.d
  app:
    image: my-node-app
    ports:
      - 8080:8080
