/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos, and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 - 2022 George MacKerron
Released under the MIT licence: see LICENCE file
*/

declare module 'zapatos/schema' {

  import type * as db from 'zapatos/db';

  // got a type error on schemaVersionCanary below? update by running `npx zapatos`
  export interface schemaVersionCanary extends db.SchemaVersionCanary { version: 104 }


  /* === schema: public === */

  /* --- enums --- */

  export type Status = 'Blocked' | 'Done' | 'In-Progress' | 'Not_Started';
  export namespace every {
    export type Status = ['Blocked', 'Done', 'In-Progress', 'Not_Started'];
  }

  /* --- tables --- */

  /**
   * **task**
   * - Table in database
   */
  export namespace task {
    export type Table = 'task';
    export interface Selectable {
      /**
      * **task.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id: string;
      /**
      * **task.title**
      * - `text` in database
      * - `NOT NULL`, default: `''::text`
      */
      title: string;
      /**
      * **task.description**
      * - `text` in database
      * - Nullable, no default
      */
      description: string | null;
      /**
      * **task.status**
      * - `Status` in database
      * - Nullable, default: `'Not_Started'::"Status"`
      */
      status: Status | null;
      /**
      * **task.created**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      created: Date;
      /**
      * **task.updated**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updated: Date;
    }
    export interface JSONSelectable {
      /**
      * **task.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id: string;
      /**
      * **task.title**
      * - `text` in database
      * - `NOT NULL`, default: `''::text`
      */
      title: string;
      /**
      * **task.description**
      * - `text` in database
      * - Nullable, no default
      */
      description: string | null;
      /**
      * **task.status**
      * - `Status` in database
      * - Nullable, default: `'Not_Started'::"Status"`
      */
      status: Status | null;
      /**
      * **task.created**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      created: db.TimestampString;
      /**
      * **task.updated**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updated: db.TimestampString;
    }
    export interface Whereable {
      /**
      * **task.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **task.title**
      * - `text` in database
      * - `NOT NULL`, default: `''::text`
      */
      title?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **task.description**
      * - `text` in database
      * - Nullable, no default
      */
      description?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **task.status**
      * - `Status` in database
      * - Nullable, default: `'Not_Started'::"Status"`
      */
      status?: Status | db.Parameter<Status> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, Status | db.Parameter<Status> | db.SQLFragment | db.ParentColumn>;
      /**
      * **task.created**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      created?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **task.updated**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updated?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **task.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment;
      /**
      * **task.title**
      * - `text` in database
      * - `NOT NULL`, default: `''::text`
      */
      title?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment;
      /**
      * **task.description**
      * - `text` in database
      * - Nullable, no default
      */
      description?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **task.status**
      * - `Status` in database
      * - Nullable, default: `'Not_Started'::"Status"`
      */
      status?: Status | db.Parameter<Status> | null | db.DefaultType | db.SQLFragment;
      /**
      * **task.created**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      created?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment;
      /**
      * **task.updated**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updated?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **task.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.DefaultType | db.SQLFragment>;
      /**
      * **task.title**
      * - `text` in database
      * - `NOT NULL`, default: `''::text`
      */
      title?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.DefaultType | db.SQLFragment>;
      /**
      * **task.description**
      * - `text` in database
      * - Nullable, no default
      */
      description?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **task.status**
      * - `Status` in database
      * - Nullable, default: `'Not_Started'::"Status"`
      */
      status?: Status | db.Parameter<Status> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, Status | db.Parameter<Status> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **task.created**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      created?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment>;
      /**
      * **task.updated**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updated?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'task_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **user**
   * - Table in database
   */
  export namespace user {
    export type Table = 'user';
    export interface Selectable {
      /**
      * **user.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id: string;
      /**
      * **user.firstName**
      * - `text` in database
      * - `NOT NULL`, default: `''::text`
      */
      firstName: string;
      /**
      * **user.lastName**
      * - `text` in database
      * - `NOT NULL`, default: `''::text`
      */
      lastName: string;
      /**
      * **user.created**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      created: Date;
      /**
      * **user.updated**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updated: Date;
    }
    export interface JSONSelectable {
      /**
      * **user.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id: string;
      /**
      * **user.firstName**
      * - `text` in database
      * - `NOT NULL`, default: `''::text`
      */
      firstName: string;
      /**
      * **user.lastName**
      * - `text` in database
      * - `NOT NULL`, default: `''::text`
      */
      lastName: string;
      /**
      * **user.created**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      created: db.TimestampString;
      /**
      * **user.updated**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updated: db.TimestampString;
    }
    export interface Whereable {
      /**
      * **user.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **user.firstName**
      * - `text` in database
      * - `NOT NULL`, default: `''::text`
      */
      firstName?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **user.lastName**
      * - `text` in database
      * - `NOT NULL`, default: `''::text`
      */
      lastName?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **user.created**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      created?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **user.updated**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updated?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **user.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment;
      /**
      * **user.firstName**
      * - `text` in database
      * - `NOT NULL`, default: `''::text`
      */
      firstName?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment;
      /**
      * **user.lastName**
      * - `text` in database
      * - `NOT NULL`, default: `''::text`
      */
      lastName?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment;
      /**
      * **user.created**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      created?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment;
      /**
      * **user.updated**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updated?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **user.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.DefaultType | db.SQLFragment>;
      /**
      * **user.firstName**
      * - `text` in database
      * - `NOT NULL`, default: `''::text`
      */
      firstName?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.DefaultType | db.SQLFragment>;
      /**
      * **user.lastName**
      * - `text` in database
      * - `NOT NULL`, default: `''::text`
      */
      lastName?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.DefaultType | db.SQLFragment>;
      /**
      * **user.created**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      created?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment>;
      /**
      * **user.updated**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updated?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'user_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **userTask**
   * - Table in database
   */
  export namespace userTask {
    export type Table = 'userTask';
    export interface Selectable {
      /**
      * **userTask.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id: string;
      /**
      * **userTask.userId**
      * - `uuid` in database
      * - Nullable, no default
      */
      userId: string | null;
      /**
      * **userTask.taskId**
      * - `uuid` in database
      * - Nullable, no default
      */
      taskId: string | null;
      /**
      * **userTask.created**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      created: Date;
      /**
      * **userTask.updated**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updated: Date;
    }
    export interface JSONSelectable {
      /**
      * **userTask.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id: string;
      /**
      * **userTask.userId**
      * - `uuid` in database
      * - Nullable, no default
      */
      userId: string | null;
      /**
      * **userTask.taskId**
      * - `uuid` in database
      * - Nullable, no default
      */
      taskId: string | null;
      /**
      * **userTask.created**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      created: db.TimestampString;
      /**
      * **userTask.updated**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updated: db.TimestampString;
    }
    export interface Whereable {
      /**
      * **userTask.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **userTask.userId**
      * - `uuid` in database
      * - Nullable, no default
      */
      userId?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **userTask.taskId**
      * - `uuid` in database
      * - Nullable, no default
      */
      taskId?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **userTask.created**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      created?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **userTask.updated**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updated?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **userTask.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment;
      /**
      * **userTask.userId**
      * - `uuid` in database
      * - Nullable, no default
      */
      userId?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **userTask.taskId**
      * - `uuid` in database
      * - Nullable, no default
      */
      taskId?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **userTask.created**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      created?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment;
      /**
      * **userTask.updated**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updated?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **userTask.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `uuid_generate_v4()`
      */
      id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.DefaultType | db.SQLFragment>;
      /**
      * **userTask.userId**
      * - `uuid` in database
      * - Nullable, no default
      */
      userId?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **userTask.taskId**
      * - `uuid` in database
      * - Nullable, no default
      */
      taskId?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **userTask.created**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      created?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment>;
      /**
      * **userTask.updated**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updated?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'userTask_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /* --- aggregate types --- */

  export namespace public {  
    export type Table = task.Table | user.Table | userTask.Table;
    export type Selectable = task.Selectable | user.Selectable | userTask.Selectable;
    export type JSONSelectable = task.JSONSelectable | user.JSONSelectable | userTask.JSONSelectable;
    export type Whereable = task.Whereable | user.Whereable | userTask.Whereable;
    export type Insertable = task.Insertable | user.Insertable | userTask.Insertable;
    export type Updatable = task.Updatable | user.Updatable | userTask.Updatable;
    export type UniqueIndex = task.UniqueIndex | user.UniqueIndex | userTask.UniqueIndex;
    export type Column = task.Column | user.Column | userTask.Column;
  
    export type AllBaseTables = [task.Table, user.Table, userTask.Table];
    export type AllForeignTables = [];
    export type AllViews = [];
    export type AllMaterializedViews = [];
    export type AllTablesAndViews = [task.Table, user.Table, userTask.Table];
  }



  /* === global aggregate types === */

  export type Schema = 'public';
  export type Table = public.Table;
  export type Selectable = public.Selectable;
  export type JSONSelectable = public.JSONSelectable;
  export type Whereable = public.Whereable;
  export type Insertable = public.Insertable;
  export type Updatable = public.Updatable;
  export type UniqueIndex = public.UniqueIndex;
  export type Column = public.Column;

  export type AllSchemas = ['public'];
  export type AllBaseTables = [...public.AllBaseTables];
  export type AllForeignTables = [...public.AllForeignTables];
  export type AllViews = [...public.AllViews];
  export type AllMaterializedViews = [...public.AllMaterializedViews];
  export type AllTablesAndViews = [...public.AllTablesAndViews];


  /* === lookups === */

  export type SelectableForTable<T extends Table> = {
    "task": task.Selectable;
    "user": user.Selectable;
    "userTask": userTask.Selectable;
  }[T];

  export type JSONSelectableForTable<T extends Table> = {
    "task": task.JSONSelectable;
    "user": user.JSONSelectable;
    "userTask": userTask.JSONSelectable;
  }[T];

  export type WhereableForTable<T extends Table> = {
    "task": task.Whereable;
    "user": user.Whereable;
    "userTask": userTask.Whereable;
  }[T];

  export type InsertableForTable<T extends Table> = {
    "task": task.Insertable;
    "user": user.Insertable;
    "userTask": userTask.Insertable;
  }[T];

  export type UpdatableForTable<T extends Table> = {
    "task": task.Updatable;
    "user": user.Updatable;
    "userTask": userTask.Updatable;
  }[T];

  export type UniqueIndexForTable<T extends Table> = {
    "task": task.UniqueIndex;
    "user": user.UniqueIndex;
    "userTask": userTask.UniqueIndex;
  }[T];

  export type ColumnForTable<T extends Table> = {
    "task": task.Column;
    "user": user.Column;
    "userTask": userTask.Column;
  }[T];

  export type SQLForTable<T extends Table> = {
    "task": task.SQL;
    "user": user.SQL;
    "userTask": userTask.SQL;
  }[T];

}
